### ISSUE TITLE
Table not fully transferred in Oracle to Postgres transfer

### ISSUE THREAD

**Issue by atanasg** [sqlpipe/sqlpipe#10]
We have an Oracle table with approx. 26 mio rows. When using sqlpipe from the command line we see that after 2-3mio entries there is no more transfer of further rows. However, the executable seems still active. After approx. 20min. the executable stops with "Transfer complete. We make a good team!" which is misleading.

**Comment by calmitchell617** [comment]
Hi, thanks for the bug report. Can you provide more detail?

1. Source system (seems like it is Oracle)
2. Target system (also oracle?)
3. Version numbers of both systems
4. Are there any logs being output by the executable?

**Comment by atanasg** [comment]
@calmitchell617 Thank you for the fast feedback! 

1. Oracle Database 19c Enterprise Edition Release 19.0.0.0.0
2. PostgreSQL 14.2, compiled by Visual C++ build 1914, 64-bit
3. see above
4. No, sqlpipe.exe just reports "Transfer complete. We make a good team!" after 20Min. In another attempts it even does not terminate, but we see that after the first 2-3mio entries there are no new rows being inserted into the target.

**Comment by calmitchell617** [comment]
My initial thought is that the Oracle driver I'm using https://github.com/sijms/go-ora might be timing out. 

I wonder if @[sijms](https://github.com/sijms) could chime in?

**Comment by calmitchell617** [comment]
This error should be fixed by the new version of SQLpipe. It uses SQLLDR to transfer data, instead of writing SQL statements.
