### ISSUE TITLE
SQL Server -> Snowflake throws an error

### ISSUE THREAD

**Issue by rkolosky** [sqlpipe/sqlpipe#11]
I'm attempting to copy a SQL Server database to Snowflake, but whe I run the command, it appears that SQL Server throws an error.

It responds with map[dsType:mssql error:parse "sqlserver://<username>:<Password>@<host address>:<port>?database=<databaseName>": net/url: invalid userinfo query:<queryLine>] db.Query() threw an error

I don't see an error log generated in the same directory, nor do I see anything showing in the Event log. I verified I can login to SQL Server Management studio from the same machine sqlpipe is running on using the username and password, so it shouldn't be a connectivity issue.

**Comment by calmitchell617** [comment]
Hi there,

That is supposed to be a connectivity string, are you sure you're passing in connection info? Can you give an example of the command you're running (with any sensitive data removed)?

**Comment by rkolosky** [comment]
Hi Cal -
I have found a different way to get data in, so I have forgotten what the command I was using.

**Comment by calmitchell617** [comment]
Hi, great. Sorry for the delayed reply. Closing.
