### ISSUE TITLE
query connect to oracle 11g ,returns query:xxx] db.Query() threw an error. But it works well when connect to oracle 12c

### ISSUE THREAD

**Issue by villagervv** [sqlpipe/sqlpipe#13]
I use sqlpipe to transfer data from oracle to postgresql.
I have two oracle db.
When I transfer from oracle 11g. it returns query: query clause] db.Query() threw an error.
ORA-06512: at line 6
map[dsType: oracle error : ORA-06502 :/PL/SQL: numeric or value error]

I user query command. Also the same return info.

**Comment by calmitchell617** [comment]
Hello,

This is probably a bug in SQLpipe's code, which stems from a mis-matching of DB types.

I am currently replacing the driver I'm using for Oracle (and indeed, the rest of the data sources), with an ODBC driver. This will make it a lot easier to match DB types, and may resolve the bug on its own. I'm going to leave the issue open for now.

**Comment by calmitchell617** [comment]
Hi, this is an old issue, but the latest version of SQLpipe should fix this error. Closing for now, please re-open if you have any other issues.
