### ISSUE TITLE
Upsert feature request

### ISSUE THREAD

**Issue by sadhasivam** [sqlpipe/sqlpipe#14]
Are we considering an upsert feature for the data transfer use case? 
If a primary key exists, then update else, insert kind of feature. 

Would there be any Data Mapping feature between source result set to Sink schema?

**Comment by calmitchell617** [comment]
Hi there,

What type of system are you trying to upsert into?

**Comment by calmitchell617** [comment]
Hello,

I've added upserting to SQLpipe pro, however, it is a paid product.
