### ISSUE TITLE
invalid memory address or nil pointer dereference when calling v2/transfer source:PostgreSQL target:MSSQL

### ISSUE THREAD

**Issue by pogacnikp** [sqlpipe/sqlpipe#20]
```
$Body = '{"source": 
{"odbc_dsn": "Driver=PostgreSQL;Server=host.docker.internal;Port=5432;Database=database;Uid=tester;Pwd=****;"}, 
"target": { "system_type": "postgres", "odbc_dsn": "Driver=PostgreSQL;Server=host.docker.internal;Port=5432;Database=database;Uid=tester;Pwd=****;",
   "table": "test", "schema": "public" 
 },  "query": "select * from test"
}'

$Parameters = @{
    Method = "POST"
    Uri =  "http://localhost:9000/v2/transfer"
    Body = $Body
    ContentType = "application/json"
}

Invoke-RestMethod @Parameters
```

After runnig the above code in PowerShell ISE i get the next error:
Invoke-RestMethod : {
	"error": "runtime error: invalid memory address or nil pointer dereference"
}

**Comment by calmitchell617** [comment]
Hi there,

The new version of SQLpipe should fix this error. However, it only runs on Linux.

You can still run it using Docker, if you are on a Windows machine, however. The project README should have all the info you need to get started with the new version.

Please re-open if you have any other issues.
