### ISSUE TITLE
snowflake odbc driver invalid path 

### ISSUE THREAD

**Issue by bhushanamk** [sqlpipe/sqlpipe#21]
docker installed at /snowflake_odbc (root) whereas  the snowflake.driver.template refer /home/ubuntu/snowflake_odbc

    "error": "SQLDriverConnect: {01000} [unixODBC][Driver Manager]Can't open lib '/home/ubuntu/snowflake_odbc/lib/libSnowflake.so' : file not found"

**Comment by calmitchell617** [comment]
Hi there, thanks for reporting. I'll look into it.

**Comment by HelenCampbell** [comment]
I've hit this issue myself today, looks like the driver installation location isn't correct in the template. Opened a fix here:

https://github.com/sqlpipe/sqlpipe/pull/31

For other users working with the dockerfile, simply open a bash terminal in the running docker file and edit `driver-templates/snowflake.driver.template` in situ with the update defined in the PR above.

**Comment by calmitchell617** [comment]
Hi, the latest version of SQLpipe should fix this - it now uses the native Go Snowflake Driver.
