### ISSUE TITLE
MySQL; Error 1064: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by andro42** [sqlpipe/sqlpipe#29]
When importing from Microsoft SQL to MySQL there is an error when importing value \\' (backslash and single quote) error occurs:
"map[dsType:mysql error:Error 1064: You have an error in your SQL syntax;".

When I reconstructed the insert statement after logic in valFormaters.go looks like:
`INSERT INTO msg (message_text) VALUES ('\''');`
Original value of [message_text]: "\\'".
And that statement results in error.

I suggest Escaping the escape character for MySQL (maybe PostgreSQL also):
https://github.com/sqlpipe/sqlpipe/blob/main/internal/engine/transfers/formatters/shared/valFormatters.go
var dbValReplacer = strings.NewReplacer(\`'\`, \`''\`, "{", "(", "}", ")")
--> (for mysql)
var dbValReplacer = strings.NewReplacer(\`'\`, \`''\`, "{", "(", "}", ")", \`\\\`, \`\\\\\`)

In that case the insert statement would look like:
`INSERT INTO msg (message_text) VALUES ('\\''');`
which is valid statement and exactly the value of the source.

**Comment by calmitchell617** [comment]
Hi there, thanks for the feedback.

The latest version of SQLpipe now uses CSVs instead of writing SQL queries. It also allows you specify escape / delimter characters. I'm going to close this, please re-open if you're still having the issue.
