### ISSUE TITLE
Handling backslash in SQL Server database server name, within BAT file

### ISSUE THREAD

**Issue by davidmwilliams** [sqlpipe/sqlpipe#39]
SQL Server allows _instances_, so sometimes a database server may be in the form HOSTNAME\INSTANCENAME

I'm having a lot of difficulty working out how to escape the slash so it is accepted by SQLPipe, or rather, so it passes it to Go's dbQuery ok, from a BAT file in Windows.

(NOTE: I am using the v1 command-line tool sqlpipe.exe, which doesn't seem to appear on this site anymore. There are various reasons why installing/running Docker is overkill. The command-line version was very convenient.)

For example ...

```bat
sqlpipe transfer ^
--source-ds-type mssql ^
--source-hostname "host\instance" ^
--source-port 1433 ^
etc
```

gives

`map[dsType:mssql error:parse "sqlserver://user:pass@host\\instance:1433?database=db": invalid character "\\" in host name query:...;] db.Query() threw an error`

As you can see, SQLPIPE has changed the \ to \\, so if I try and escape it in the command line (i.e., use \\) then the error simply becomes a problem with invalid character "\\\\".

I also tried using %5c to no effect, I tried to use the backtick thinking that would pass to Go but I couldn't figure it out.

What can I do here to make this work?

Thank you!

**Comment by calmitchell617** [comment]
Hi David,

Sorry, I don't support V1 anymore. 

Maybe try a triple backslash? I don't remember adding any escapement logic to the handling of input params in V1, so it's probably just an exercise in finding the right input string.

For what it's worth, the latest version of SQLpipe does not require Docker, it just has a dependency depending on the target system. psql for PostgreSQL targets, sqlldr for oracle, or bcp for SQL Server.

If you're finding it convenient to use the command line arguments to pass connection info, that wouldn't be too difficult to add to the latest version. Let me know if that's something useful for you.

**Comment by davidmwilliams** [comment]
Oh how wonderful, thank you @calmitchell617 !

If command line arguments were available for the new v2 edition, and if I could deploy it without Docker then that would be awesome and definitely help immensely.

**Comment by calmitchell617** [comment]
David, I just pushed an update to allow for triggering transfers via the CLI.

However, I just realized that you're using Windows, the latest version of SQLpipe only runs on Linux with AMD64 processors. So, it may or may not be helpful to you, depending on your platform flexbility.

In any case, there is now an example of triggering transfers via the CLI in the README.

**Comment by calmitchell617** [comment]
Closing, since I won't be supporting V1, and won't be adding Windows support.

**Comment by davidmwilliams** [comment]
Thanks; yes - using Windows. Any chance you might re-release the v1 source code for those of us on Windows?

**Comment by calmitchell617** [comment]
Yes, it is available here https://github.com/sqlpipe/sqlpipe/tree/aeb798bf67b6ae46a8d16c134810cd6c79739529

Unfortunately the docs are no longer live.

**Comment by davidmwilliams** [comment]
That's awesome, thanks so much, @calmitchell617 !
