### ISSUE TITLE
Incorrect conversion of booleans during migration from PostgreSQL to Oracle

### ISSUE THREAD

**Issue by mmarkow22** [sqlpipe/sqlpipe#40]
Hi,

I'm working on migration from PostgreSQL to Oracle.
It seems that when there is boolean column in PostgreSQL during migration it's always converted to 0 in Oracle - regardless of it's true or false.

Source table (PostgreSQL)
```
create table source_table
(
    id bigint not null constraint pk_source_table primary key,
    active boolean
);
```

Destination table (Oracle)
```
create table dest_table
(
    ID NUMBER(38) not null constraint PK_DEST_TABLE primary key,
    ACTIVE NUMBER(1)
);
```

Source table contains one row: 1,true

Resulting pipe file is OK:
```
1,true
```

Resulting final CSV file is incorrect:
```
1,0
```

In result destination table contains incorrect data: 1,0

I think that error is in the `system_oracle getFinalCsvFormatters()` function.
Maybe this part
```
"bool": func(v string) (string, error) {
  if v == "1" {
    return "1", nil
  }
  return "0", nil
},
```
should be changed into
```
"bool": func(v string) (string, error) {
  if v == "1" || v == "true"  {
    return "1", nil
  }
  return "0", nil
},
```

**Comment by calmitchell617** [comment]
Hi, thanks for this report. I will look into it shortly.

**Comment by calmitchell617** [comment]
Hi, sorry it took me a while to get to this. I made the change - can you please give it a try, if you haven't made the fix locally already?

**Comment by mmarkow22** [comment]
Hi, thank you. 
Yes, we made fix locally - as a workaround.
Looking at your change, this should work but I can't test it on the arm64 image.
Could you please create amd64 image?

**Comment by calmitchell617** [comment]
Yes, I just published it.

It was actually a mistake that it was ARM64 - I built it on my macbook and forgot the build tag :-) thanks for the feedback.
