### ISSUE TITLE
MSSQL not handling self-signed certificates in the usual way

### ISSUE THREAD

**Issue by ibrentlam** [sqlpipe/sqlpipe#41]
Same failure on pre-built binary and self-built. Here's the command to copy from PostgreSQL to MS SQL Server and the griping about self-signed certificate. 
Usually the TrustServerCertificate=true or =yes as in the connection string below works around this. Please advise. 

#!/bin/bash
# read lots of configs from the env file
.  /var/lib/rundeck/bin/sqlpipe/orgs.env

# make the call
/usr/local/bin/sqlpipe \
        -cli-transfer \
        -create-target-table-if-not-exists \
        -drop-target-table-if-exists \
        -source-name ${source_name}\
        -source-type ${source_type} \
        -source-connection-string ${source_type}://${source_user}:${source_pass}@${source_host}:5432/${source_db} \
        -source-schema ${source_schema} \
        -source-table orgs \
        -target-name ${target_name} \
        -target-type ${target_type} \
        -target-connection-string "Server=${target_host},${target_port};Database=${target_db};User Id=${target_user};Password=${target_pass};Encrypt=true;TrustServerCertificate=true;" \
        -target-database ${target_db} \
        -target-hostname ${target_host},${target_port} \
        -target-username ${target_user} \
        -target-password ${target_pass} \
        -target-schema dbo \
        -target-table orgs

result:
WARNING 2023/12/21 16:13:45 sqlldr not found. please install sqllder to transfer data to oracle :: exec: "sqlldr": executable file not found in $PATH ::
INFO    2023/12/21 16:13:45 temp dir /tmp/sqlpipe/86d4d9eb-203b-400a-b466-ee5854314764 created
INFO    2023/12/21 16:13:45 pipe file dir /tmp/sqlpipe/86d4d9eb-203b-400a-b466-ee5854314764/pipe-files created
INFO    2023/12/21 16:13:45 final csv dir /tmp/sqlpipe/86d4d9eb-203b-400a-b466-ee5854314764/final-csv created
INFO    2023/12/21 16:13:45 created transfer 86d4d9eb-203b-400a-b466-ee5854314764 from local-postgres to datahub-mssql
INFO    2023/12/21 16:13:45 transfer 86d4d9eb-203b-400a-b466-ee5854314764 status set to running
INFO    2023/12/21 16:13:45 dropped dbo.orgs if exists in datahub-mssql
INFO    2023/12/21 16:13:45 created table dbo.orgs if not exists in datahub-mssql
INFO    2023/12/21 16:13:45 transfer 86d4d9eb-203b-400a-b466-ee5854314764 finished writing pipe files
INFO    2023/12/21 16:13:45 transfer 86d4d9eb-203b-400a-b466-ee5854314764 finished converting pipe files
INFO    2023/12/21 16:13:45 transfer 86d4d9eb-203b-400a-b466-ee5854314764 cancelled
INFO    2023/12/21 16:13:45 transfer 86d4d9eb-203b-400a-b466-ee5854314764 status set to error
ERROR   2023/12/21 16:13:45 transfers.go:703: error running transfer 86d4d9eb-203b-400a-b466-ee5854314764 :: error inserting pipe files :: error inserting final csvs :: error inserting final csv :: failed to upload csv to mssql :: stderr exit status 1 :: stdout SQLState = 08001, NativeError = -1
Error = [Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:0A000086:SSL routines::certificate verify failed:self-signed certificate]
SQLState = 08001, NativeError = -1
Error = [Microsoft][ODBC Driver 18 for SQL Server]Client unable to establish connection. For solutions related to encryption errors, see https://go.microsoft.com/fwlink/?linkid=2226722

**Comment by ibrentlam** [comment]
found the docs, have to put the accept certificate in the hostname!

**Comment by davidmwilliams** [comment]
@ibrentlam could you share an example of your solution? Thanks.
