### ISSUE TITLE
Large table will have issue when run the transfer

### ISSUE THREAD

**Issue by shawnlu-ikigai** [sqlpipe/sqlpipe#42]
I have a table with lot of records.
`SELECT count(*) FROM ACTIVITY;`
`Result:30663298`
I saw this error on the transfer:
```
"status": "error",
"error": "error running transfer 1bb8dbfc-40e3-40a2-a442-3ef3f1866ffa :: error inserting pipe files :: error inserting final csvs :: error inserting final csv :: error getting file num :: error converting file number to int :: strconv.Atoi: parsing \"00000000000011110100001001000000\": value out of range",
```

I think the value `00000000000011110100001001000000` is 1000000. Do we have any limitation on the number of records in a table?

**Comment by calmitchell617** [comment]
That is strange, the atoi function shouldn't go out of range until over 2 billion, as far as I know. I just changed that function to parse to int64, can you please try again?

**Comment by shawnlu-ikigai** [comment]
It works now, thank you @calmitchell617
