### ISSUE TITLE
 Please help me, or I will be fired!!! File Registered problem?

### ISSUE THREAD

**Issue by Vincent990413** [sqlpipe/sqlpipe#43]
![image](https://github.com/sqlpipe/sqlpipe/assets/45600829/24537ccf-fb14-40bb-9e79-8c1c225bd589)

What can I do to fix this problem? It seems to be a File permission problem? But I got all the admin permission! Please help me, or I will be fired!!!

**Comment by calmitchell617** [comment]
Hi, looks like you are running on windows. SQLpipe only works on Linux.

Are you using the SQLpipe docker image?

**Comment by calmitchell617** [comment]
https://hub.docker.com/r/sqlpipe/sqlpipe

**Comment by Vincent990413** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
