### ISSUE TITLE
Feature : Trigger a webhook api post completion 

### ISSUE THREAD

**Issue by bheemvennapureddy** [sqlpipe/sqlpipe#48]
Usecase: its hard to understand when the task gets completed, it would be great if we build some kind of a trigger webhook post completion if provided as input. Also an ability to give an estimated completion time based on the input query will be a great addition

**Comment by bheemvennapureddy** [comment]
@calmitchell617 thoughts ?

**Comment by calmitchell617** [comment]
What is hard about long polling?

**Comment by bheemvennapureddy** [comment]
You mean to say keep polling until the task gets completed?

**Comment by bheemvennapureddy** [comment]
Polling can be inefficient because we need send requests at regular intervals, even if there's no new event. Webhooks are more efficient for our use case is what I feel

**Comment by calmitchell617** [comment]
I agree that it is marginally less efficient, but there are not many use cases that can't be accomplished with long polling. I will not have the time to implement that feature, but feel free to make a PR.

**Comment by bheemvennapureddy** [comment]
@calmitchell617 is there a way you can add a feature for estimated time taken if there is a query input to estimate the copy time ? Is there a way we can do that ?

**Comment by bheemvennapureddy** [comment]
Closing this for now
