### ISSUE TITLE
Cloudera (Hive or Impala) Connector

### ISSUE THREAD

**Issue by fogartjj** [sqlpipe/sqlpipe#5]
Request to add a Cloudera (Hive or Impala) as a data connector (specifically as a data source). 

Use Case: As a data engineer I have a local postgresql cluster that I pull data into to run my data analysis. One of my new datasets is a cloudera cluster and I've been fighting with different tools to pull it into psql - haven't found any other successful tools yet. Yours gave me high hopes but you didn't have the cloudera connector listed so I was curious how easy of a lift it is to add cloudera as a system type.

**Comment by calmitchell617** [comment]
Closing, this won't be a priority in the near term.
